require: rubocop-rails

Style/Documentation:
  Exclude:
    - db/**/*
    - config/*
    - test/*
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
